/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.Dimension;

/**
 *
 * @author thaua
 */
public class FormPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        btAbrirFormBolsa = new javax.swing.JMenu();
        menuFormBolsa = new javax.swing.JMenuItem();
        menuFormVendedor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuFormMovimentacoes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DesktopPane.setBackground(java.awt.SystemColor.control);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(126, 40));

        btAbrirFormBolsa.setText("CADASTROS");

        menuFormBolsa.setText("Bolsa");
        menuFormBolsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormBolsaActionPerformed(evt);
            }
        });
        btAbrirFormBolsa.add(menuFormBolsa);

        menuFormVendedor.setText("Vendedor");
        menuFormVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormVendedorActionPerformed(evt);
            }
        });
        btAbrirFormBolsa.add(menuFormVendedor);

        jMenuBar1.add(btAbrirFormBolsa);

        jMenu2.setText("Movimentações");

        menuFormMovimentacoes.setText("Movimentação");
        menuFormMovimentacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFormMovimentacoesActionPerformed(evt);
            }
        });
        jMenu2.add(menuFormMovimentacoes);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFormBolsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormBolsaActionPerformed

        FormBolsa form = new FormBolsa();
        DesktopPane.add(form);
        Dimension desktopSize = DesktopPane.getSize();
        Dimension jInternalFrameSize = form.getSize();

        int x = (desktopSize.width - jInternalFrameSize.width) / 2;
        int y = (desktopSize.height - jInternalFrameSize.height) / 2;

        form.setLocation(x, y);
        form.setVisible(true);
    }//GEN-LAST:event_menuFormBolsaActionPerformed

    private void menuFormVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormVendedorActionPerformed

        FormVendedor form = new FormVendedor();
        DesktopPane.add(form);

        Dimension desktopSize = DesktopPane.getSize();
        Dimension jInternalFrameSize = form.getSize();

        int x = (desktopSize.width - jInternalFrameSize.width) / 2;
        int y = (desktopSize.height - jInternalFrameSize.height) / 2;

        form.setLocation(x, y);
        form.setVisible(true);

    }//GEN-LAST:event_menuFormVendedorActionPerformed

    private void menuFormMovimentacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFormMovimentacoesActionPerformed
        // TODO add your handling code here:
        FormMovimentacoess form = new FormMovimentacoess();
        DesktopPane.add(form);

        Dimension desktopSize = DesktopPane.getSize();
        Dimension jInternalFrameSize = form.getSize();

        int x = (desktopSize.width - jInternalFrameSize.width) / 2;
        int y = (desktopSize.height - jInternalFrameSize.height) / 2;

        form.setLocation(x, y);
        form.setVisible(true);
    }//GEN-LAST:event_menuFormMovimentacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenu btAbrirFormBolsa;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuFormBolsa;
    private javax.swing.JMenuItem menuFormMovimentacoes;
    private javax.swing.JMenuItem menuFormVendedor;
    // End of variables declaration//GEN-END:variables
}
